[[libsodium]]
arch = "aarch64"
git-tree-sha1 = "3f80d40fad5202e9d3b9cd8aa9b04f70c8c84871"
os = "macos"

    [[libsodium.download]]
    sha256 = "fb855c1b8513443c5d23497071aea184d419fc6dbe0d730e0da8ce51abbdf839"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.20+1/libsodium.v1.0.20.aarch64-apple-darwin.tar.gz"
[[libsodium]]
arch = "aarch64"
git-tree-sha1 = "75befafe6d017d0c9ff6071627f1cb10ebeef660"
libc = "glibc"
os = "linux"

    [[libsodium.download]]
    sha256 = "00a160316c2e1801fe9ef24aaff241302f15e46b3288f81e5a480e360f625efc"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.20+1/libsodium.v1.0.20.aarch64-linux-gnu.tar.gz"
[[libsodium]]
arch = "aarch64"
git-tree-sha1 = "c37eabd44034f8a956b17e7bc71e4c2f9f97796e"
libc = "musl"
os = "linux"

    [[libsodium.download]]
    sha256 = "c0112c1e104155443257914f3c8b273e07452d63bb8f033be46aae853aa55fc6"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.20+1/libsodium.v1.0.20.aarch64-linux-musl.tar.gz"
[[libsodium]]
arch = "aarch64"
git-tree-sha1 = "5360e528a58fbd441fbfda3aa4942d1dd1c1cee0"
os = "freebsd"

    [[libsodium.download]]
    sha256 = "5c45482c167e226c8994f0a0e14773c30d7fdacf8f9a3625248ffefd1c09e595"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.20+1/libsodium.v1.0.20.aarch64-unknown-freebsd.tar.gz"
[[libsodium]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2b8b151ceb0f8cd8e852c60711490fa308bfc35e"
libc = "glibc"
os = "linux"

    [[libsodium.download]]
    sha256 = "4fd6686cfa65d65cba1aa5ab046ea37fe94d8e8c89959f7f1d9d9c0ea50c066e"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.20+1/libsodium.v1.0.20.armv6l-linux-gnueabihf.tar.gz"
[[libsodium]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a72a183d799c22825056ffec191cfd81c3da4d91"
libc = "musl"
os = "linux"

    [[libsodium.download]]
    sha256 = "f1cad1784ca1f9efe32f9474b8ffce43bd81173c6acd6e167f385024425e7d4e"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.20+1/libsodium.v1.0.20.armv6l-linux-musleabihf.tar.gz"
[[libsodium]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "78ea9b2687866124568379e5e771b3fdeee4c82d"
libc = "glibc"
os = "linux"

    [[libsodium.download]]
    sha256 = "f6d24e1b258bd7bc6f46ef1fba77a58ecd58fc205dd3421d57dafc81a9802f8b"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.20+1/libsodium.v1.0.20.armv7l-linux-gnueabihf.tar.gz"
[[libsodium]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c120f2a3a753904d6001338ae97603f3c197a845"
libc = "musl"
os = "linux"

    [[libsodium.download]]
    sha256 = "704309dcd959420ab34db458645e0d80df9abfd06a3bff73f8694dffdb08c6b6"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.20+1/libsodium.v1.0.20.armv7l-linux-musleabihf.tar.gz"
[[libsodium]]
arch = "i686"
git-tree-sha1 = "7c506913de164e0b31366c5a08f731060105c3d7"
libc = "glibc"
os = "linux"

    [[libsodium.download]]
    sha256 = "feae4a9aedabf84db812bda8106609cdb488f56cae5321fa590630006dc0e8e3"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.20+1/libsodium.v1.0.20.i686-linux-gnu.tar.gz"
[[libsodium]]
arch = "i686"
git-tree-sha1 = "c7d120b1c88e35fd914afa5efe714e4284fa3f81"
libc = "musl"
os = "linux"

    [[libsodium.download]]
    sha256 = "781bfa87b8ea8d0a20be4277d9c696e4e7a3506043d8e771b362fc314b236b27"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.20+1/libsodium.v1.0.20.i686-linux-musl.tar.gz"
[[libsodium]]
arch = "i686"
git-tree-sha1 = "581672d02a39043270cc3a3f96572ba13dae0ec1"
os = "windows"

    [[libsodium.download]]
    sha256 = "ccc3dcb4b1de3d04bf9f830c6e1f49178fec18f0ab3dd13fd8f4277af5fd4310"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.20+1/libsodium.v1.0.20.i686-w64-mingw32.tar.gz"
[[libsodium]]
arch = "powerpc64le"
git-tree-sha1 = "7b46baf40f5bad9423577d002b45a9541a91eb0e"
libc = "glibc"
os = "linux"

    [[libsodium.download]]
    sha256 = "2b71f3bd97c614d4cd74e8bc91ef63bf8234a893e92a8b23717cea7970794de5"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.20+1/libsodium.v1.0.20.powerpc64le-linux-gnu.tar.gz"
[[libsodium]]
arch = "x86_64"
git-tree-sha1 = "ac8d41c8b60fd1a03912dc08abf57ef531635600"
os = "macos"

    [[libsodium.download]]
    sha256 = "da6092326cd4bffcaaf507c937d721c0cb4e85d083ee976eda7e7c3f24b8234b"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.20+1/libsodium.v1.0.20.x86_64-apple-darwin.tar.gz"
[[libsodium]]
arch = "x86_64"
git-tree-sha1 = "f29d4f826e041900a7e9975dac2959d85ff26fca"
libc = "glibc"
os = "linux"

    [[libsodium.download]]
    sha256 = "8ba05b9ce1f2d05275074a7477874eab22ce194ccfde5b09c573ecd783635319"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.20+1/libsodium.v1.0.20.x86_64-linux-gnu.tar.gz"
[[libsodium]]
arch = "x86_64"
git-tree-sha1 = "9a50f7961fafce31f75b7f5818b34dbc139acd81"
libc = "musl"
os = "linux"

    [[libsodium.download]]
    sha256 = "19f61ec493b59909efc4231d582943b5d25fc6e7f79e09ace720ed4f3bf4184d"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.20+1/libsodium.v1.0.20.x86_64-linux-musl.tar.gz"
[[libsodium]]
arch = "x86_64"
git-tree-sha1 = "ec3122dc81fdda1a70e014ba592ad6c125e9126f"
os = "freebsd"

    [[libsodium.download]]
    sha256 = "14a4f1e961440753bfcd95174236be6b884dd620f91b3f2ba983e378f89a1572"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.20+1/libsodium.v1.0.20.x86_64-unknown-freebsd.tar.gz"
[[libsodium]]
arch = "x86_64"
git-tree-sha1 = "ec9e66da4e7cbcb28094ccc081ffd2216b7cea51"
os = "windows"

    [[libsodium.download]]
    sha256 = "9272d868a2560d058e98afefd829213eb234abf4003cf6001ad0b49ccc5d7cf1"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.20+1/libsodium.v1.0.20.x86_64-w64-mingw32.tar.gz"
