[[libsodium]]
arch = "aarch64"
git-tree-sha1 = "8e3089dc047c3972ded087ab655c74ff5fea3282"
libc = "glibc"
os = "linux"

    [[libsodium.download]]
    sha256 = "1e62313090796e38a37dac2c5c4e267aefbbcd99cc283c99e669113aec5e3538"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.19+0/libsodium.v1.0.19.aarch64-linux-gnu.tar.gz"
[[libsodium]]
arch = "aarch64"
git-tree-sha1 = "dcd05621f1e64bb501cccdc9e0fdda7c83198645"
libc = "musl"
os = "linux"

    [[libsodium.download]]
    sha256 = "f251bdfbf3335d12769bf2882899f038c6c9d4c5b8667183e29a9d0c3b9014b2"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.19+0/libsodium.v1.0.19.aarch64-linux-musl.tar.gz"
[[libsodium]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2541afd102a8b09a61e105a98b2566c864a590a3"
libc = "glibc"
os = "linux"

    [[libsodium.download]]
    sha256 = "1e617945e8181fdbf8dbbbed78d888749ea662c1af9162b213d239fd19c59d59"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.19+0/libsodium.v1.0.19.armv7l-linux-gnueabihf.tar.gz"
[[libsodium]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9a4908b657169d275756f07357e8a6c4228d4966"
libc = "musl"
os = "linux"

    [[libsodium.download]]
    sha256 = "33f74d9e772b8b40b54ec0de9b078319f79c806610d8cfda1d7328d435987f9c"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.19+0/libsodium.v1.0.19.armv7l-linux-musleabihf.tar.gz"
[[libsodium]]
arch = "i686"
git-tree-sha1 = "175d9a69b1f3c1c6eda5766401f7759757804fed"
libc = "glibc"
os = "linux"

    [[libsodium.download]]
    sha256 = "51184df00053aaac30d939e95eba0feb5341c816b602ad8bcef2fcc06791064b"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.19+0/libsodium.v1.0.19.i686-linux-gnu.tar.gz"
[[libsodium]]
arch = "i686"
git-tree-sha1 = "9d758a1e1d3230a9b474cf5d7dbfeb0bbac177e7"
libc = "musl"
os = "linux"

    [[libsodium.download]]
    sha256 = "ef42a16e94f296a4f8bbfc576fe1fc18b75a4f46178305565d463b441838a907"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.19+0/libsodium.v1.0.19.i686-linux-musl.tar.gz"
[[libsodium]]
arch = "i686"
git-tree-sha1 = "7e54de4eaf45b72ac408868dac9201f97b7a9214"
os = "windows"

    [[libsodium.download]]
    sha256 = "4f866b41c0fe5024d5cc0502bde38424a190829462f86f35c28116b3983fa73a"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.19+0/libsodium.v1.0.19.i686-w64-mingw32.tar.gz"
[[libsodium]]
arch = "powerpc64le"
git-tree-sha1 = "68f949183d37491786c5adc2e2c3979951be6ef3"
libc = "glibc"
os = "linux"

    [[libsodium.download]]
    sha256 = "85478394120f4584bf902c17a79cfe8104d43533cf76a8f43116c06756d7f131"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.19+0/libsodium.v1.0.19.powerpc64le-linux-gnu.tar.gz"
[[libsodium]]
arch = "x86_64"
git-tree-sha1 = "bf831c88a22c02156d5b4302268e547864f0a19e"
os = "macos"

    [[libsodium.download]]
    sha256 = "b0cf149d088935514d44970527bae775dde0045d535355897bf0029b9dd39c09"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.19+0/libsodium.v1.0.19.x86_64-apple-darwin.tar.gz"
[[libsodium]]
arch = "x86_64"
git-tree-sha1 = "30680a637e165a5a1733175b03449eb8f7c2fe4b"
libc = "glibc"
os = "linux"

    [[libsodium.download]]
    sha256 = "37e8401e83386fb719f9867381842fedb3fa7edcf0f4af6d87d6441ca7d277f9"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.19+0/libsodium.v1.0.19.x86_64-linux-gnu.tar.gz"
[[libsodium]]
arch = "x86_64"
git-tree-sha1 = "bf048ffc93c87897572e4cd84dbf55b0c11f524b"
libc = "musl"
os = "linux"

    [[libsodium.download]]
    sha256 = "9e05c53d015fb0d481469551e9e5cf96a2bda1f9ca7f38e69ff8b174d52d383d"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.19+0/libsodium.v1.0.19.x86_64-linux-musl.tar.gz"
[[libsodium]]
arch = "x86_64"
git-tree-sha1 = "3f59cc6c747e98e0c6408843336a4de7f12bfdba"
os = "freebsd"

    [[libsodium.download]]
    sha256 = "d4155382943131c2824958a6ab1b3a1ac8ea64cd393c80b3ba5eb23ed1fc6e1d"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.19+0/libsodium.v1.0.19.x86_64-unknown-freebsd.tar.gz"
[[libsodium]]
arch = "x86_64"
git-tree-sha1 = "4a425e4fe5cd2442a5713cf7cd5633d4937195d1"
os = "windows"

    [[libsodium.download]]
    sha256 = "1fda45c546d179c84c8cfb4142490d7909f78a1accca9ab3d5cc13e6ed3de99f"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.19+0/libsodium.v1.0.19.x86_64-w64-mingw32.tar.gz"
