[[libsodium]]
arch = "i686"
git-tree-sha1 = "f62db4acc82b675c654424ef76a99e440f64d5fe"
libc = "musl"
os = "linux"

    [[libsodium.download]]
    sha256 = "27f2b9c11f2af14c9e78a43dd47840f92d3dd34b073d3579958c4f8bee70dedc"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.18+1/libsodium.v1.0.18.i686-linux-musl.tar.gz"
[[libsodium]]
arch = "aarch64"
git-tree-sha1 = "79d9648f3c394c893138786873b7fa74dbd75596"
libc = "musl"
os = "linux"

    [[libsodium.download]]
    sha256 = "48042de76b0dd3fb52ac95227e14b3e1839f095bee8742dc7e192313d731e361"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.18+1/libsodium.v1.0.18.aarch64-linux-musl.tar.gz"
[[libsodium]]
arch = "i686"
git-tree-sha1 = "8a779acbccd1b19077cd85da76220f521615cec0"
os = "windows"

    [[libsodium.download]]
    sha256 = "b6bf73d69fa44461c223c9c28a0cea0fe984c61c07ed87b7f44e17184412a7e1"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.18+1/libsodium.v1.0.18.i686-w64-mingw32.tar.gz"
[[libsodium]]
arch = "x86_64"
git-tree-sha1 = "8718acede03acc3fce73f98050c281e255429642"
os = "windows"

    [[libsodium.download]]
    sha256 = "586f41c53fa28601e6d80f8b57411dc0097bf03cf1b1f51afa49e5626de4575c"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.18+1/libsodium.v1.0.18.x86_64-w64-mingw32.tar.gz"
[[libsodium]]
arch = "armv7l"
git-tree-sha1 = "1e4a1361e386e37462e827cc4117ad0bce9914bd"
libc = "glibc"
os = "linux"

    [[libsodium.download]]
    sha256 = "a497bc786441b5f002422c12d69ac3cb96572fc218a4205b912c0c86ebdfd553"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.18+1/libsodium.v1.0.18.armv7l-linux-gnueabihf.tar.gz"
[[libsodium]]
arch = "armv7l"
git-tree-sha1 = "e79711029639b2633bb5c9d78b946d9761bc9328"
libc = "musl"
os = "linux"

    [[libsodium.download]]
    sha256 = "ea14a9905615b52485e5aac60315222e75f5bce485f47bf19dd8eda11e79ce3c"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.18+1/libsodium.v1.0.18.armv7l-linux-musleabihf.tar.gz"
[[libsodium]]
arch = "i686"
git-tree-sha1 = "8817ab05b7d8091f4f2f54307fef1d27c92b67af"
libc = "glibc"
os = "linux"

    [[libsodium.download]]
    sha256 = "1c2221fd24e103b00810efd5cc6cdc1257de6e825064d58097389a0f0caea7ac"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.18+1/libsodium.v1.0.18.i686-linux-gnu.tar.gz"
[[libsodium]]
arch = "x86_64"
git-tree-sha1 = "53913caaf6afb8d02133a1fdc6eec5112c9f7be1"
libc = "glibc"
os = "linux"

    [[libsodium.download]]
    sha256 = "997e80e7180be64f9c9e057ead0a970511fcc0ee7b88dc63694f97d0a778fc8b"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.18+1/libsodium.v1.0.18.x86_64-linux-gnu.tar.gz"
[[libsodium]]
arch = "powerpc64le"
git-tree-sha1 = "ee3387cf04035970a722cc9fac20530f66f51608"
libc = "glibc"
os = "linux"

    [[libsodium.download]]
    sha256 = "621d151bc05cbc916dda3948331f0c3ddc8104d4481737d959ffd2b4f655c750"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.18+1/libsodium.v1.0.18.powerpc64le-linux-gnu.tar.gz"
[[libsodium]]
arch = "x86_64"
git-tree-sha1 = "d9060da25204d407aaf9d89ae67a161d7e3a27e8"
os = "macos"

    [[libsodium.download]]
    sha256 = "e2ac585b20873df5ed24e7ce417c0d88bc410afdac01b9082309a6435cc76757"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.18+1/libsodium.v1.0.18.x86_64-apple-darwin14.tar.gz"
[[libsodium]]
arch = "aarch64"
git-tree-sha1 = "bf78ae0cfdfdc5291acacc46d17f08a769535a15"
libc = "glibc"
os = "linux"

    [[libsodium.download]]
    sha256 = "6c2b83befd8ae3d3f9d3555d1ddf08323becf4e183981941511fd32641a082b0"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.18+1/libsodium.v1.0.18.aarch64-linux-gnu.tar.gz"
[[libsodium]]
arch = "x86_64"
git-tree-sha1 = "4b0fefebe91f6a60a5488d2602c42a57e346c892"
os = "freebsd"

    [[libsodium.download]]
    sha256 = "aa222da8f597fa5ab108e9897c5ce26db6aaa0dea3374921d535ff2695541a55"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.18+1/libsodium.v1.0.18.x86_64-unknown-freebsd11.1.tar.gz"
[[libsodium]]
arch = "x86_64"
git-tree-sha1 = "11f4ff8726890b7c4d6124b1e76431497449916b"
libc = "musl"
os = "linux"

    [[libsodium.download]]
    sha256 = "42a47b81c5529a11216fe1d38c5a2a87a37d4137f856fc7a5ebcf6b111e2686e"
    url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.18+1/libsodium.v1.0.18.x86_64-linux-musl.tar.gz"
