# Autogenerated wrapper script for libsodium_jll for aarch64-apple-darwin
export libsodium

JLLWrappers.@generate_wrapper_header("libsodium")
JLLWrappers.@declare_library_product(libsodium, "@rpath/libsodium.23.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libsodium,
        "lib/libsodium.23.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
