# Autogenerated wrapper script for libsodium_jll for x86_64-w64-mingw32
export libsodium

JLLWrappers.@generate_wrapper_header("libsodium")
JLLWrappers.@declare_library_product(libsodium, "libsodium-23.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libsodium,
        "bin\\libsodium-23.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
